#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Feature: Build Detail Page - Clickable Metrics Filter

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/home/ewyct/dev/lastest2"
cd "$PROJECT_ROOT"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

if ! command -v pnpm &> /dev/null; then
    echo -e "${RED}pnpm not found. Please install pnpm first.${NC}"
    exit 1
fi

if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    pnpm install
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."

# Frontend (Next.js)
pnpm dev &
FRONTEND_PID=$!

# Wait for frontend
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Test URL:"
echo "  Build Detail Page: http://localhost:3000/builds/d6cdd584-82b5-4750-bdff-0d41e79ba825"
echo ""
echo "To stop the server, press Ctrl+C or run:"
echo "  kill $FRONTEND_PID"
echo ""
