/**
 * Parses test code to extract structured TestAssertion[] metadata.
 * Recognizes assertion patterns generated by event-to-code.ts and hand-written patterns.
 */

import type { TestAssertion } from '@/lib/db/schema';
import { createHash } from 'crypto';

/**
 * Generate a stable ID for an assertion based on its properties.
 */
function assertionId(orderIndex: number, type: string, selector?: string, expected?: string): string {
  const input = `${orderIndex}:${type}:${selector ?? ''}:${expected ?? ''}`;
  return createHash('sha256').update(input).digest('hex').slice(0, 12);
}

/**
 * Parse test code and extract structured assertion metadata.
 */
export function parseAssertions(code: string): TestAssertion[] {
  const assertions: TestAssertion[] = [];
  const lines = code.split('\n');
  let orderIndex = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // Pattern 1: Element assertion block (from event-to-code.ts)
    // // Element assertion: toBeVisible  OR  // Hard assertion: toBeVisible
    const elementCommentMatch = trimmed.match(/^\/\/ (Element|Hard) assertion: (\w+)/);
    if (elementCommentMatch) {
      const isHard = elementCommentMatch[1] === 'Hard';
      const assertionType = elementCommentMatch[2];
      const assertion = parseElementAssertionBlock(lines, i, orderIndex, assertionType);
      if (assertion) {
        assertion.isSoft = !isHard;
        assertions.push(assertion);
        orderIndex++;
      }
      continue;
    }

    // Pattern 2: Page-level assertions
    // await expect(page).toHaveURL(...)
    const pageAssertionMatch = trimmed.match(/await\s+expect\(page\)\.(not\.)?(\w+)\((.*)?\)/);
    if (pageAssertionMatch) {
      const negated = !!pageAssertionMatch[1];
      const assertionType = pageAssertionMatch[2];
      const argStr = pageAssertionMatch[3] ?? '';
      const expectedValue = extractStringArg(argStr);

      assertions.push({
        id: assertionId(orderIndex, assertionType, 'page', expectedValue),
        orderIndex,
        category: 'page',
        assertionType,
        negated,
        expectedValue,
        isSoft: true,
        label: describeAssertion('page', assertionType, negated, undefined, expectedValue),
        codeLineStart: i + 1,
        codeLineEnd: i + 1,
      });
      orderIndex++;
      continue;
    }

    // Pattern 3: Inline expect(el) assertions (not in a block)
    const inlineElMatch = trimmed.match(/await\s+expect\((\w+)\)\.(not\.)?(\w+)\((.*)?\)/);
    if (inlineElMatch && inlineElMatch[1] !== 'page') {
      const negated = !!inlineElMatch[2];
      const assertionType = inlineElMatch[3];
      const argStr = inlineElMatch[4] ?? '';
      const expectedValue = extractStringArg(argStr);

      assertions.push({
        id: assertionId(orderIndex, assertionType, inlineElMatch[1], expectedValue),
        orderIndex,
        category: 'element',
        assertionType,
        negated,
        expectedValue,
        isSoft: true,
        label: describeAssertion('element', assertionType, negated, undefined, expectedValue),
        codeLineStart: i + 1,
        codeLineEnd: i + 1,
      });
      orderIndex++;
      continue;
    }

    // Pattern 4: Generic value assertions
    // expect(someVar).toBe(...)
    const genericMatch = trimmed.match(/expect\(([^)]+)\)\.(not\.)?(\w+)\((.*)?\)/);
    if (genericMatch && !trimmed.includes('await') && !genericMatch[1].match(/^(page|el|element)$/)) {
      const negated = !!genericMatch[2];
      const assertionType = genericMatch[3];
      const argStr = genericMatch[4] ?? '';
      const expectedValue = extractStringArg(argStr);

      assertions.push({
        id: assertionId(orderIndex, assertionType, genericMatch[1], expectedValue),
        orderIndex,
        category: 'generic',
        assertionType,
        negated,
        expectedValue,
        isSoft: true,
        label: describeAssertion('generic', assertionType, negated, genericMatch[1], expectedValue),
        codeLineStart: i + 1,
        codeLineEnd: i + 1,
      });
      orderIndex++;
      continue;
    }

    // Pattern 5: Page wait assertions
    if (trimmed.match(/await\s+page\.waitForLoadState\(/)) {
      const stateMatch = trimmed.match(/waitForLoadState\(['"](\w+)['"]\)/);
      const state = stateMatch?.[1] ?? 'load';
      assertions.push({
        id: assertionId(orderIndex, 'waitForLoadState', 'page', state),
        orderIndex,
        category: 'page',
        assertionType: 'waitForLoadState',
        negated: false,
        expectedValue: state,
        isSoft: true,
        label: `Page load state: ${state}`,
        codeLineStart: i + 1,
        codeLineEnd: i + 1,
      });
      orderIndex++;
      continue;
    }
  }

  return assertions;
}

function parseElementAssertionBlock(
  lines: string[],
  commentLine: number,
  orderIndex: number,
  assertionType: string,
): TestAssertion | null {
  // Look for the locateWithFallback call and expect call in the following lines
  let targetSelector: string | undefined;
  let targetSelectors: Array<{ type: string; value: string }> | undefined;
  let expectedValue: string | undefined;
  let attributeName: string | undefined;
  let negated = false;
  let endLine = commentLine;

  for (let j = commentLine + 1; j < Math.min(commentLine + 10, lines.length); j++) {
    const l = lines[j].trim();

    // Parse selector from locateWithFallback
    const selectorMatch = l.match(/locateWithFallback\(page,\s*(\[.*?\])/);
    if (selectorMatch) {
      try {
        targetSelectors = JSON.parse(selectorMatch[1]);
        if (targetSelectors && targetSelectors.length > 0) {
          targetSelector = `${targetSelectors[0].type}: ${targetSelectors[0].value}`;
        }
      } catch {
        // Ignore parse errors
      }
    }

    // Parse the expect assertion
    const expectMatch = l.match(/await\s+expect\(el\)\.(not\.)?(\w+)\((.*)?\)/);
    if (expectMatch) {
      negated = !!expectMatch[1];
      const args = expectMatch[3] ?? '';

      if (assertionType === 'toHaveAttribute') {
        const attrMatch = args.match(/['"]([^'"]+)['"]\s*,\s*['"]([^'"]*)['"]/);
        if (attrMatch) {
          attributeName = attrMatch[1];
          expectedValue = attrMatch[2];
        }
      } else {
        expectedValue = extractStringArg(args);
      }

      endLine = j;
      break;
    }

    // End of block
    if (l === '}') {
      endLine = j;
      break;
    }
  }

  return {
    id: assertionId(orderIndex, assertionType, targetSelector, expectedValue),
    orderIndex,
    category: 'element',
    assertionType,
    negated,
    targetSelector,
    targetSelectors,
    expectedValue,
    attributeName,
    isSoft: true,
    label: describeAssertion('element', assertionType, negated, targetSelector, expectedValue, attributeName),
    codeLineStart: commentLine + 1,
    codeLineEnd: endLine + 1,
  };
}

function extractStringArg(argStr: string): string | undefined {
  const str = argStr.trim();
  if (!str) return undefined;

  // String literal
  const stringMatch = str.match(/^['"](.*)['"]$/);
  if (stringMatch) return stringMatch[1];

  // buildUrl pattern
  const buildUrlMatch = str.match(/buildUrl\(baseUrl,\s*['"]([^'"]+)['"]\)/);
  if (buildUrlMatch) return buildUrlMatch[1];

  // RegExp
  const regexMatch = str.match(/^\/(.+)\/([gimsuy]*)$/);
  if (regexMatch) return `/${regexMatch[1]}/${regexMatch[2]}`;

  // Number
  const numMatch = str.match(/^(\d+(?:\.\d+)?)$/);
  if (numMatch) return numMatch[1];

  return str;
}

function describeAssertion(
  category: string,
  type: string,
  negated: boolean,
  target?: string,
  expected?: string,
  attributeName?: string,
): string {
  const not = negated ? ' not' : '';
  const prefix = target ? `"${target}"` : (category === 'page' ? 'Page' : 'Element');

  switch (type) {
    case 'toBeVisible': return `${prefix} is${not} visible`;
    case 'toBeHidden': return `${prefix} is${not} hidden`;
    case 'toBeAttached': return `${prefix} is${not} attached`;
    case 'toBeEnabled': return `${prefix} is${not} enabled`;
    case 'toBeDisabled': return `${prefix} is${not} disabled`;
    case 'toBeChecked': return `${prefix} is${not} checked`;
    case 'toHaveText': return `${prefix} has${not} text "${expected ?? '...'}"`;
    case 'toContainText': return `${prefix}${not} contains text "${expected ?? '...'}"`;
    case 'toHaveValue': return `${prefix} has${not} value "${expected ?? '...'}"`;
    case 'toHaveAttribute': return `${prefix} has${not} attribute ${attributeName}="${expected ?? '...'}"`;
    case 'toHaveURL': return `Page URL${not} matches "${expected ?? '...'}"`;
    case 'toHaveTitle': return `Page title${not} matches "${expected ?? '...'}"`;
    case 'toBe': return `Value is${not} ${expected ?? '...'}`;
    case 'toEqual': return `Value${not} equals ${expected ?? '...'}`;
    case 'toBeTruthy': return `Value is${not} truthy`;
    case 'toBeFalsy': return `Value is${not} falsy`;
    case 'toHaveCount': return `${prefix} has${not} count ${expected ?? '...'}`;
    case 'toHaveStyle': return `${prefix} has${not} style "${expected ?? '...'}"`;
    case 'waitForLoadState': return `Page load state: ${expected ?? 'load'}`;
    default: return `${prefix}${not} ${type}(${expected ?? ''})`;
  }
}
