/**
 * Pre-computed lookups shared by every doc renderer, built once per
 * `renderDocs` call from the {@link ClassifiedSnapshot}.
 */
import { orgSettingsOf } from "../model/baseline";
import {
  DEFAULT_CLASSIFICATION_RULES,
  countriesFromWhereClause,
  repTypeCountsFor,
} from "../model/classify";
import {
  GLOBAL_COUNTRY,
  type ClassificationRule,
  type ClassifiedProfile,
  type ClassifiedSnapshot,
  type CountryCode,
  type CountryRef,
  type LayoutConfig,
  type OrgSnapshot,
  type ProfileConfig,
  type RepCategory,
  type VmocConfig,
} from "../model/types";
import { cmp, code, sorted, unique } from "./markdown";

export interface RenderOptions {
  /** Clock for the "generated" stamp in every file header; omitted → no stamp. */
  now?: () => Date;
  /** Title of the index page. Default: `Veeva CRM configuration — <org name or instance URL>`. */
  title?: string;
  /** Classification rules to document in `README.md`. Default: `DEFAULT_CLASSIFICATION_RULES`. */
  rules?: readonly ClassificationRule[];
}

export const CATEGORY_LABELS: Record<RepCategory, string> = {
  sales_rep: "Sales rep",
  specialty_rep: "Specialty rep",
  kam: "Key account manager",
  msl: "MSL",
  manager: "Manager",
  inside_sales: "Inside sales",
  admin: "Admin",
  other: "Other",
};

export function categoryLabel(category: RepCategory | string): string {
  return (CATEGORY_LABELS as Record<string, string>)[category] ?? category;
}

/** Country code as a directory name (codes are ISO-2, but unknown raw names are kept by extraction). */
export function dirName(code: CountryCode): string {
  return code.replace(/[^A-Za-z0-9_-]+/g, "_");
}

export interface Ctx {
  classified: ClassifiedSnapshot;
  snapshot: OrgSnapshot;
  title: string;
  /** Blockquote line with snapshot provenance, placed under every H1. */
  header: string;
  rules: readonly ClassificationRule[];
  /** `SettingObject.Field` → rendered org default. */
  orgSettings: Record<string, string>;
  /** `Object.RecordType` → active flag, from the object catalogue. */
  recordTypeActive: Map<string, boolean>;
  /** Layout full name → layout, from the object catalogue. */
  layoutsByName: Map<string, LayoutConfig>;
  /** Layout full name → countries whose profiles are assigned it. */
  layoutCountries: Map<string, Set<CountryCode>>;
  /** Country → `LanguageLocaleKey` → active users (from the user summary). */
  languagesByCountry: Map<CountryCode, Map<string, number>>;
  /** Objects known to the org: catalogue + every object with a permission row. */
  knownObjects: Set<string>;
  countryRef(code: CountryCode): CountryRef | undefined;
}

export function buildContext(
  classified: ClassifiedSnapshot,
  options: RenderOptions = {},
): Ctx {
  const snapshot = classified.snapshot;
  const title =
    options.title ??
    `Veeva CRM configuration — ${snapshot.orgName ?? snapshot.instanceUrl}`;
  const headerParts = [
    `Snapshot: ${code(snapshot.instanceUrl)}`,
    `extracted ${code(snapshot.extractedAt)}`,
    `API ${code(snapshot.apiVersion)}`,
  ];
  if (options.now)
    headerParts.push(`generated ${code(options.now().toISOString())}`);
  const header =
    "<!-- Generated by @lastest/veeva-crm-migration from a Veeva CRM snapshot. Re-run `veeva-crm-migration document` instead of editing. -->\n" +
    `> ${headerParts.join(" · ")}`;

  const recordTypeActive = new Map<string, boolean>();
  const layoutsByName = new Map<string, LayoutConfig>();
  const knownObjects = new Set<string>();
  for (const o of snapshot.objects) {
    knownObjects.add(o.apiName);
    for (const rt of o.recordTypes)
      recordTypeActive.set(`${o.apiName}.${rt.developerName}`, rt.active);
    for (const l of o.layouts) layoutsByName.set(l.fullName, l);
  }
  for (const p of snapshot.profiles)
    for (const op of p.objectPermissions) knownObjects.add(op.object);

  const layoutCountries = new Map<string, Set<CountryCode>>();
  for (const cp of classified.profiles) {
    for (const la of cp.profile.layoutAssignments) {
      const set = layoutCountries.get(la.layout) ?? new Set<CountryCode>();
      for (const c of cp.countries) set.add(c);
      layoutCountries.set(la.layout, set);
    }
  }

  const languagesByCountry = new Map<CountryCode, Map<string, number>>();
  for (const u of snapshot.users ?? []) {
    if (!u.language) continue;
    const langs =
      languagesByCountry.get(u.country) ?? new Map<string, number>();
    langs.set(u.language, (langs.get(u.language) ?? 0) + u.activeUsers);
    languagesByCountry.set(u.country, langs);
  }

  const refs = new Map(snapshot.countries.map((c) => [c.code, c]));
  for (const c of classified.countries)
    if (!refs.has(c.country.code)) refs.set(c.country.code, c.country);

  return {
    classified,
    snapshot,
    title,
    header,
    rules: options.rules ?? DEFAULT_CLASSIFICATION_RULES,
    orgSettings: orgSettingsOf(snapshot),
    recordTypeActive,
    layoutsByName,
    layoutCountries,
    languagesByCountry,
    knownObjects,
    countryRef: (c) => refs.get(c),
  };
}

// ---------------------------------------------------------------------------
// Small derived facts used by several renderers
// ---------------------------------------------------------------------------

export function totalUsers(profile: ProfileConfig): number {
  return Object.values(profile.activeUsersByCountry).reduce((a, b) => a + b, 0);
}

/** Active users of a profile in a country; the GLOBAL bucket counts every user. */
export function usersIn(profile: ProfileConfig, country: CountryCode): number {
  return country === GLOBAL_COUNTRY
    ? totalUsers(profile)
    : (profile.activeUsersByCountry[country] ?? 0);
}

/** `DE 10, FR 5` sorted by count then code. */
export function usersByCountry(profile: ProfileConfig): string {
  return sorted(
    Object.entries(profile.activeUsersByCountry).filter(([, n]) => n > 0),
    ([, n]) => -n,
    ([c]) => c,
  )
    .map(([c, n]) => `${c} ${n}`)
    .join(", ");
}

/** DESIGN §2.2 / §5.1 disposition column. */
export function disposition(cp: ClassifiedProfile): string {
  if (totalUsers(cp.profile) === 0) return "drop (0 active users)";
  return cp.shared ? "shared" : "keep";
}

/** Languages (`LanguageLocaleKey`) in use in a country, most users first. */
export function languagesOf(ctx: Ctx, country: CountryCode): string[] {
  const langs = ctx.languagesByCountry.get(country);
  if (!langs) return [];
  return sorted(
    [...langs.entries()],
    ([, n]) => -n,
    ([l]) => l,
  ).map(([l]) => l);
}

/** `de` for `de_DE` / `de-DE` / `de`. */
export function langBase(lang: string): string {
  return lang.toLowerCase().split(/[_-]/)[0] ?? "";
}

/** `User_Type_vod__c` values of a set of profiles (country-filtered when the user summary allows). */
export function userTypesOf(
  ctx: Ctx,
  profiles: readonly ClassifiedProfile[],
  country: CountryCode,
): string[] {
  const counts = new Map<string, number>();
  const names = new Set(profiles.map((p) => p.profile.name));
  const ids = new Set(profiles.map((p) => p.profile.id));
  const fromUsers = (ctx.snapshot.users ?? []).filter(
    (u) =>
      (ids.has(u.profileId) || names.has(u.profileName)) &&
      u.userType &&
      (country === GLOBAL_COUNTRY || u.country === country),
  );
  if (fromUsers.length) {
    for (const u of fromUsers)
      counts.set(u.userType!, (counts.get(u.userType!) ?? 0) + u.activeUsers);
  } else {
    for (const p of profiles)
      for (const [t, n] of Object.entries(
        repTypeCountsFor(p.profile, ctx.snapshot.users),
      ))
        counts.set(t, (counts.get(t) ?? 0) + n);
  }
  return sorted(
    [...counts.entries()],
    ([, n]) => -n,
    ([t]) => t,
  ).map(([t, n]) => `${t} (${n})`);
}

/** Countries a VMOC where clause filters on. */
export function vmocCountries(v: VmocConfig): string[] {
  return unique(countriesFromWhereClause(v.whereClause));
}

export function byName<T extends { name: string }>(a: T, b: T): number {
  return cmp(a.name, b.name);
}

export function profilesSorted(
  profiles: readonly ClassifiedProfile[],
): ClassifiedProfile[] {
  return sorted(profiles, (p) => p.profile.name);
}
