/**
 * `sample_transaction` — `Sample_Transaction_vod__c` → `sample_transaction__v`
 * (spec §6.3.35, §6.1 step 18, §6.2, §3.3, §4.4, §8.6).
 *
 * Regulated transactional rows (PDMA): scope is the OR of the per-type date
 * fields (`Call_Date`, `Transferred_Date`, `Adjusted_Date`, `Submitted_Date`,
 * `CreatedDate`) widened by `scope.sampleRetentionMonths` (family `samples`),
 * attributed to the owning rep's country with the account as fallback
 * (`['user:OwnerId', 'account']`), never deleted on the target (`ignore`).
 *
 * **Sample load strategy** (`objects.sample_transaction.load.sampleStrategy`,
 * per country; applies jointly to the whole samples family):
 *  - `noTriggersRecalc` (default): `noTriggers = true`, `state__v` submitted,
 *    then `postLoad.recalculateRollups` per touched `sample_lot__v` /
 *    `sample_inventory__v` (probe 17 — downgraded to `noTriggersVerify` with
 *    `SAMPLE_STRATEGY_DOWNGRADED` when the action is missing; blocking in the
 *    US overlay unless `fallbackStrategy` is named).
 *  - `noTriggersVerify`: no recalc; VQL roll-up verification per lot against
 *    the extracted `Calculated_Quantity_vod__c` (`sample_lot`) **and** the
 *    tool's recomputation Σ `signedQuantity(...)` of loaded submitted rows.
 *  - `triggersOnTransactions`: `noTriggers = false` here (`call2_sample` stays
 *    NoTriggers); trigger rejections are retried NoTriggers per batch
 *    (`load.sampleTriggerRejectFallback`, default true).
 *  - `triggersOnCallSamples`: disbursements are regenerated from
 *    `call2_sample`; this object is loaded for non-disbursement types only
 *    (`TRIGGERS_ON_CALL_SAMPLES_PREDICATE`).
 * The engine reads the strategy from `mapping.load`; the module only carries
 * the defaults and the pure helpers (`isDisbursement`, `signedQuantity`).
 *
 * `account__v` is optional except on disbursements (§6.3.35 "n (Y for
 * disbursement)") — `custom(accountRef)` enforces the conditional
 * requirement and otherwise behaves exactly like `ref(account)`.
 *
 * `Ref_Transaction_Id_vod__c` is a self reference patched in pass 2
 * (§6.1 step 18 `sample_transaction.ref_transaction_id__v`).
 *
 * Every target name is `[UNV]` (DOC object, fields by rename rule): preflight
 * validates and drops what the vault lacks. `State_vod__c` (address snapshot)
 * cannot be renamed mechanically — `state__v` is the lifecycle state — so it
 * targets `state_province__v` (the confirmed exception on address/em_event).
 */
import { applyTransform } from "../../transform/registry";
import type {
  CustomTransformFn,
  SourceRow,
  TransformResult,
} from "../../types";
import { defineObject } from "../types";

/** SFDC record type / `Type_vod__c` value of disbursements. */
export const SAMPLE_TRANSACTION_DISBURSEMENT_TYPE = "Disbursement_vod";

/**
 * SOQL term appended under `triggersOnCallSamples` (§6.3.35): disbursements
 * are regenerated by Vault from `call2_sample`, every other type is loaded.
 */
export const TRIGGERS_ON_CALL_SAMPLES_PREDICATE = `Type_vod__c != '${SAMPLE_TRANSACTION_DISBURSEMENT_TYPE}'`;

/** RecordType DeveloperName → object type api name (all `[UNV]`). */
export const SAMPLE_TRANSACTION_OBJECT_TYPES: Record<string, string> = {
  Adjustment_vod: "adjustment__v",
  Disbursement_vod: "disbursement__v",
  Receipt_vod: "receipt__v",
  Return_vod: "return__v",
  Transfer_vod: "transfer__v",
};

/** `Status_vod__c` → lifecycle state (`[UNV]`, pattern of §6.3.30 `Submitted_vod → submitted_state__v`). */
export const SAMPLE_TRANSACTION_STATES: Record<string, string> = {
  Saved_vod: "saved_state__v",
  Submitted_vod: "submitted_state__v",
  In_Progress_vod: "in_progress_state__v",
};

/** Blob name of the signature image (`objects.sample_transaction.blobs.signature`; US overlay sets `required`). */
export const SAMPLE_TRANSACTION_SIGNATURE_BLOB = "signature";

/** Address / licence snapshot columns loaded verbatim (§6.3.35 "PDMA"); wildcard expansions are `[UNVERIFIED-SOURCE]`. */
export const SAMPLE_TRANSACTION_SNAPSHOT_FIELDS: ReadonlyArray<{
  source: string;
  target: string;
  transform: "text" | "longtext" | "date";
  unverifiedSource?: boolean;
}> = [
  {
    source: "Signature_Page_Display_Name_vod__c",
    target: "signature_page_display_name__v",
    transform: "text",
  },
  {
    source: "Address_Line_1_vod__c",
    target: "address_line_1__v",
    transform: "text",
  },
  {
    source: "Address_Line_2_vod__c",
    target: "address_line_2__v",
    transform: "text",
  },
  { source: "City_vod__c", target: "city__v", transform: "text" },
  { source: "State_vod__c", target: "state_province__v", transform: "text" },
  { source: "Zip_vod__c", target: "zip__v", transform: "text" },
  { source: "Zip_4_vod__c", target: "zip_4__v", transform: "text" },
  { source: "License_vod__c", target: "license__v", transform: "text" },
  {
    source: "License_Status_vod__c",
    target: "license_status__v",
    transform: "text",
    unverifiedSource: true,
  },
  {
    source: "License_Expiration_Date_vod__c",
    target: "license_expiration_date__v",
    transform: "date",
    unverifiedSource: true,
  },
  { source: "DEA_vod__c", target: "dea__v", transform: "text" },
  {
    source: "DEA_Status_vod__c",
    target: "dea_status__v",
    transform: "text",
    unverifiedSource: true,
  },
  {
    source: "DEA_Expiration_Date_vod__c",
    target: "dea_expiration_date__v",
    transform: "date",
    unverifiedSource: true,
  },
  {
    source: "DEA_Address_Line_1_vod__c",
    target: "dea_address_line_1__v",
    transform: "text",
    unverifiedSource: true,
  },
  {
    source: "DEA_Address_Line_2_vod__c",
    target: "dea_address_line_2__v",
    transform: "text",
    unverifiedSource: true,
  },
  {
    source: "DEA_City_vod__c",
    target: "dea_city__v",
    transform: "text",
    unverifiedSource: true,
  },
  {
    source: "DEA_State_vod__c",
    target: "dea_state__v",
    transform: "text",
    unverifiedSource: true,
  },
  {
    source: "DEA_Zip_vod__c",
    target: "dea_zip__v",
    transform: "text",
    unverifiedSource: true,
  },
  {
    source: "DEA_Zip_4_vod__c",
    target: "dea_zip_4__v",
    transform: "text",
    unverifiedSource: true,
  },
  { source: "CDS_vod__c", target: "cds__v", transform: "text" },
  {
    source: "CDS_Status_vod__c",
    target: "cds_status__v",
    transform: "text",
    unverifiedSource: true,
  },
  {
    source: "CDS_Expiration_Date_vod__c",
    target: "cds_expiration_date__v",
    transform: "date",
    unverifiedSource: true,
  },
  { source: "ASSMCA_vod__c", target: "assmca__v", transform: "text" },
  { source: "Credentials_vod__c", target: "credentials__v", transform: "text" },
  { source: "Salutation_vod__c", target: "salutation__v", transform: "text" },
  {
    source: "Disbursed_To_vod__c",
    target: "disbursed_to__v",
    transform: "text",
  },
  {
    source: "Disclaimer_vod__c",
    target: "disclaimer__v",
    transform: "longtext",
  },
];

/** True when the row is a disbursement (record type first, `Type_vod__c` as fallback). */
export function isDisbursement(row: SourceRow): boolean {
  const rt = row["RecordType.DeveloperName"];
  if (typeof rt === "string" && rt.trim() !== "")
    return rt.trim() === SAMPLE_TRANSACTION_DISBURSEMENT_TYPE;
  const t = row["Type_vod__c"];
  return (
    typeof t === "string" && t.trim() === SAMPLE_TRANSACTION_DISBURSEMENT_TYPE
  );
}

/**
 * Sign of a submitted transaction's `quantity__v` in the lot roll-up
 * recomputation (§6.3.35 `noTriggersVerify`): receipt / transfer-in `+`,
 * disbursement / transfer-out / return `−`, adjustment `±` (the quantity
 * carries its own sign). `objectType` is the Vault object type api name
 * (`receipt__v`, …) or the SFDC DeveloperName (`Receipt_vod`).
 */
export function rollupSign(
  objectType: string,
  opts: { transferIn?: boolean } = {},
): 1 | -1 | 0 {
  const t = objectType
    .trim()
    .toLowerCase()
    .replace(/(_vod|__v)$/, "");
  switch (t) {
    case "receipt":
      return 1;
    case "transfer":
      return opts.transferIn ? 1 : -1;
    case "disbursement":
    case "return":
      return -1;
    case "adjustment":
      return 1;
    default:
      return 0;
  }
}

/** `rollupSign(...) * quantity`; `0` for unknown types or non-numeric quantities. */
export function signedQuantity(
  objectType: string,
  quantity: unknown,
  opts: { transferIn?: boolean } = {},
): number {
  const q = typeof quantity === "number" ? quantity : Number(quantity);
  if (!Number.isFinite(q)) return 0;
  return rollupSign(objectType, opts) * q;
}

/**
 * `custom(accountRef)`: `ref(account)` whose requirement is conditional —
 * required on disbursements (`REQUIRED_MISSING`, fatal), optional otherwise.
 * An unresolved account on a disbursement is left to the normal optional
 * path (omitted now, re-pointed by the FK-consistency pass) because the
 * `required` flag of the row is what routes `pending_fk`.
 */
export const accountRef: CustomTransformFn = (
  value,
  row,
  ctx,
): TransformResult => {
  const empty = value === null || value === undefined || value === "";
  if (empty) {
    if (isDisbursement(row))
      return {
        omit: true,
        diagnostic: {
          kind: "required_missing",
          field: ctx.field.target,
          code: "REQUIRED_MISSING",
          detail: "account__v is required on disbursement transactions",
          fatal: true,
        },
      };
    return { omit: true };
  }
  return applyTransform({ kind: "ref", objectKey: "account" }, value, row, ctx);
};

export const sample_transaction = defineObject({
  key: "sample_transaction",
  source: "Sample_Transaction_vod__c",
  target: "sample_transaction__v",
  targetEvidence: "DOC",
  scope: {
    kind: "dated",
    predicates: [
      { field: "Call_Date_vod__c", type: "date" },
      { field: "Transferred_Date_vod__c", type: "date" },
      { field: "Adjusted_Date_vod__c", type: "date" },
      { field: "Submitted_Date_vod__c", type: "date" },
      { field: "CreatedDate", type: "datetime" },
    ],
    retentionFamily: "samples",
  },
  countryOf: ["user:OwnerId", "account"],
  // §6.2 lists sample_lot, account, user, call2; call2_sample is added for the
  // `ref(call2_sample)` row (step 17 precedes step 18, no cycle).
  dependsOn: ["sample_lot", "account", "user", "call2", "call2_sample"],
  selfRefs: [
    { target: "ref_transaction_id__v", source: "Ref_Transaction_Id_vod__c" },
  ],
  // Name is autoNumber (§6.0.4) — carried only with preserveAutoNumberName
  blockS: { name: "autoNumber" },
  objectTypes: { ...SAMPLE_TRANSACTION_OBJECT_TYPES },
  states: { ...SAMPLE_TRANSACTION_STATES },
  fields: [
    // --- type / lot / account
    {
      source: "Type_vod__c",
      target: "type__v",
      transform: "picklist(sample_transaction.type)",
      required: "Y",
      evidence: "UNV",
      notes: "mirrors the record type; object_type__v comes from Block S",
    },
    {
      source: "Lot_vod__c",
      target: "lot__v",
      transform: "ref(sample_lot)",
      required: "Y",
      evidence: "UNV",
      sourceType: "reference",
      notes: "master-detail → Sample_Lot",
    },
    {
      source: "Account_vod__c",
      target: "account__v",
      transform: "custom(accountRef)",
      required: "n",
      evidence: "UNV",
      sourceType: "reference",
      notes:
        "ref(account); n (Y for disbursement) — enforced by custom(accountRef)",
    },
    // --- quantities
    {
      source: "Quantity_vod__c",
      target: "quantity__v",
      transform: "number",
      required: "Y",
      evidence: "UNV",
    },
    {
      source: "Confirmed_Quantity_vod__c",
      target: "confirmed_quantity__v",
      transform: "number",
      required: "n",
      evidence: "UNV",
    },
    {
      source: "U_M_vod__c",
      target: "u_m__v",
      transform: "picklist(sample_transaction.um)",
      required: "n",
      evidence: "UNV",
      countryConfigurable: true,
      notes: "{Cases, Boxes, Units}",
    },
    // --- status (business + lifecycle, migration mode)
    {
      source: "Status_vod__c",
      target: "sample_transaction_status__v",
      transform: "picklist(sample_transaction.status)",
      required: "Y",
      evidence: "UNV",
      notes:
        "{Saved_vod, Submitted_vod, In_Progress_vod}; preflight may pick status__v when the object has no {object}_status__v",
    },
    {
      source: "Status_vod__c",
      target: "state__v",
      transform: "state(sample_transaction.state)",
      required: "Y",
      evidence: "UNV",
      notes:
        "migration mode; state names [UNV], validated against the lifecycle",
    },
    // --- call linkage
    {
      source: "Call_Date_vod__c",
      target: "call_date__v",
      transform: "date",
      required: "n",
      evidence: "UNV",
      sourceType: "date",
      notes: "scope field (disbursements)",
    },
    {
      source: "Call_Datetime_vod__c",
      target: "call_datetime__v",
      transform: "datetime",
      required: "n",
      evidence: "UNV",
      sourceType: "datetime",
    },
    {
      source: "Call_Name_vod__c",
      target: "call_name__v",
      transform: "text(100)",
      required: "n",
      evidence: "UNV",
    },
    {
      source: "Call2_vod__c",
      target: "call2__v",
      transform: "ref(call2)",
      required: "n",
      evidence: "UNV",
      sourceType: "reference",
      optionalSource: true,
      notes: "newer field — when present",
    },
    {
      source: "Call_Sample_vod__c",
      target: "call_sample__v",
      transform: "ref(call2_sample)",
      required: "n",
      evidence: "UNV",
      sourceType: "reference",
      optionalSource: true,
      notes: "newer field — when present",
    },
    // --- transfer / adjustment users
    {
      source: "Transfer_To_vod__c",
      target: "transfer_to__v",
      transform: "refUser",
      required: "n",
      evidence: "UNV",
      sourceType: "reference",
    },
    {
      source: "Transferred_From_vod__c",
      target: "transferred_from__v",
      transform: "refUser",
      required: "n",
      evidence: "UNV",
      sourceType: "reference",
    },
    {
      source: "Adjust_For_vod__c",
      target: "adjust_for__v",
      transform: "refUser",
      required: "n",
      evidence: "UNV",
      sourceType: "reference",
    },
    {
      source: "Transfer_To_Name_vod__c",
      target: "transfer_to_name__v",
      transform: "text",
      required: "n",
      evidence: "UNV",
    },
    {
      source: "Transferred_From_Name_vod__c",
      target: "transferred_from_name__v",
      transform: "text",
      required: "n",
      evidence: "UNV",
    },
    // --- per-type dates (scope fields)
    {
      source: "Transferred_Date_vod__c",
      target: "transferred_date__v",
      transform: "date",
      required: "n",
      evidence: "UNV",
      sourceType: "date",
      notes: "scope field (transfers)",
    },
    {
      source: "Adjusted_Date_vod__c",
      target: "adjusted_date__v",
      transform: "date",
      required: "n",
      evidence: "UNV",
      sourceType: "date",
      notes: "scope field (adjustments)",
    },
    {
      source: "Submitted_Date_vod__c",
      target: "submitted_date__v",
      transform: "date",
      required: "n",
      evidence: "UNV",
      sourceType: "date",
      notes: "scope field",
    },
    {
      source: "Signature_Date_vod__c",
      target: "signature_date__v",
      transform: "datetime",
      required: "n",
      evidence: "UNV",
      sourceType: "datetime",
    },
    // --- self reference (pass 2)
    {
      source: "Ref_Transaction_Id_vod__c",
      target: "ref_transaction_id__v",
      transform: "ref(sample_transaction) secondPass",
      required: "n",
      evidence: "UNV",
      sourceType: "reference",
      notes: "patched after step 18 (§6.1)",
    },
    // --- identifiers
    {
      source: "Group_Transaction_Id_vod__c",
      target: "group_transaction_id__v",
      transform: "copy",
      required: "n",
      evidence: "UNV",
      notes: "EXTID 255",
    },
    {
      source: "Shipment_ID_vod__c",
      target: "shipment_id__v",
      transform: "copy",
      required: "n",
      evidence: "UNV",
    },
    {
      source: "Sample_Card_vod__c",
      target: "sample_card__v",
      transform: "copy",
      required: "n",
      evidence: "UNV",
    },
    {
      source: "Sample_Card_Reason_vod__c",
      target: "sample_card_reason__v",
      transform: "copy",
      required: "n",
      evidence: "UNV",
    },
    // --- reason / receipt / free text
    {
      source: "Reason_vod__c",
      target: "reason__v",
      transform: "picklist(sample_transaction.reason)",
      required: "n",
      evidence: "UNV",
      countryConfigurable: true,
      notes: "20 plain-English values — derived unless crosswalked",
    },
    {
      source: "Return_To_vod__c",
      target: "return_to__v",
      transform: "picklist(sample_transaction.returnTo)",
      required: "n",
      evidence: "UNV",
      notes: "{HQ}",
    },
    {
      source: "Received_vod__c",
      target: "received__v",
      transform: "bool",
      required: "n",
      evidence: "UNV",
      sourceType: "boolean",
    },
    {
      source: "Receipt_Comments_vod__c",
      target: "receipt_comments__v",
      transform: "text",
      required: "n",
      evidence: "UNV",
    },
    {
      source: "Comments_vod__c",
      target: "comments__v",
      transform: "text",
      required: "n",
      evidence: "UNV",
    },
    {
      source: "Request_Receipt_vod__c",
      target: "request_receipt__v",
      transform: "bool",
      required: "n",
      evidence: "UNV",
      sourceType: "boolean",
    },
    {
      source: "Cold_Chain_Status_vod__c",
      target: "cold_chain_status__v",
      transform: "picklist(sample_transaction.coldChainStatus)",
      required: "n",
      evidence: "UNV",
      notes: "{In Range, Not In Range}",
    },
    {
      source: "Tag_Alert_Number_vod__c",
      target: "tag_alert_number__v",
      transform: "text",
      required: "n",
      evidence: "UNV",
    },
    {
      source: "Custom_Text_vod__c",
      target: "custom_text__v",
      transform: "text",
      required: "n",
      evidence: "UNV",
    },
    {
      source: "Manufacturer_vod__c",
      target: "manufacturer__v",
      transform: "text",
      required: "n",
      evidence: "UNV",
    },
    {
      source: "Distributor_vod__c",
      target: "distributor__v",
      transform: "text",
      required: "n",
      evidence: "UNV",
    },
    {
      source: "Lot_Name_vod__c",
      target: "lot_name__v",
      transform: "text",
      required: "n",
      evidence: "UNV",
    },
    {
      source: "Sample_vod__c",
      target: "sample__v",
      transform: "text",
      required: "n",
      evidence: "UNV",
    },
    // --- owner
    {
      source: "OwnerId",
      target: "ownerid__v",
      transform: "refUser",
      required: "y?",
      evidence: "UNV",
      notes: "queue owners → §3.4",
    },
    // --- signature + address/licence snapshot (PDMA; US overlay makes the blob required)
    {
      source: "Signature_vod__c",
      target: "signature__v",
      transform: `deferredBlob(${SAMPLE_TRANSACTION_SIGNATURE_BLOB})`,
      required: "n",
      evidence: "UNV",
      countryConfigurable: true,
      blobName: SAMPLE_TRANSACTION_SIGNATURE_BLOB,
      notes: "blob pass (§8.6); objects.sample_transaction.blobs.signature",
    },
    ...SAMPLE_TRANSACTION_SNAPSHOT_FIELDS.map((f) => ({
      source: f.source,
      target: f.target,
      transform: f.transform,
      required: "n" as const,
      evidence: "UNV" as const,
      countryConfigurable: true,
      unverifiedSource: f.unverifiedSource,
      notes: "PDMA snapshot, verbatim",
    })),
    // --- skipped (Unlock_vod__c follows its Block S row, gated by loadUnlockFlag)
    {
      source: "zvod_Sample_Lines_vod__c",
      target: "zvod_sample_lines__v",
      transform: "skip",
      required: "-",
      notes: "zvod_* layout field",
    },
    {
      source: "Discrepancy_vod__c",
      target: "discrepancy__v",
      transform: "skip",
      required: "-",
      notes: "formula — Vault recomputes",
    },
    {
      source: "Inventory_Impact_Quantity_vod__c",
      target: "inventory_impact_quantity__v",
      transform: "skip",
      required: "-",
      notes: "formula — Vault recomputes",
    },
    {
      source: "Group_Identifier_vod__c",
      target: "group_identifier__v",
      transform: "skip",
      required: "-",
      notes: "formula",
    },
  ],
  picklists: {
    "sample_transaction.type": { ...SAMPLE_TRANSACTION_OBJECT_TYPES },
    "sample_transaction.um": {
      Cases: "cases__v",
      Boxes: "boxes__v",
      Units: "units__v",
    },
    "sample_transaction.status": {
      Saved_vod: "saved__v",
      Submitted_vod: "submitted__v",
      In_Progress_vod: "in_progress__v",
    },
    "sample_transaction.reason": {},
    "sample_transaction.returnTo": { HQ: "hq__v" },
    "sample_transaction.coldChainStatus": {
      "In Range": "in_range__v",
      "Not In Range": "not_in_range__v",
    },
  },
  deletePolicy: "ignore",
  createPolicy: "create",
  load: {
    noTriggers: true,
    sampleStrategy: "noTriggersRecalc",
    sampleTriggerRejectFallback: true,
  },
  match: [
    { method: "legacy_id" },
    {
      method: "mobile_id",
      keys: [{ target: "mobile_id__v", source: "Mobile_ID_vod__c" }],
    },
  ],
  blobs: { [SAMPLE_TRANSACTION_SIGNATURE_BLOB]: "optional" },
  custom: { accountRef },
  notes:
    "Regulated transactional rows (§6.3.35). Load mode per objects.sample_transaction.load.sampleStrategy (default noTriggersRecalc; US overlay adds fallbackStrategy triggersOnTransactions); VQL roll-up verification via signedQuantity(). Deleted rows are ignored on the target and listed for review (§4.4).",
});
