#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 004: Automatic Error Detection in Smoke Tests

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Change to project directory
cd /home/ewyct/dev/lastest2

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PRE-FLIGHT CHECKS
# ============================================

echo ""
echo "Running pre-flight checks..."

# Check if pnpm is available
if ! command -v pnpm &> /dev/null; then
    echo -e "${RED}pnpm is not installed. Please install pnpm first.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ pnpm is available${NC}"

# Check if node_modules exists, if not run install
if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    pnpm install
fi
echo -e "${GREEN}✓ Dependencies installed${NC}"

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."

# Start the Next.js dev server
pnpm dev &
DEV_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Next.js Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Development Server PID: $DEV_PID"
echo ""
echo "To stop the server, run: kill $DEV_PID"
echo ""
echo "========================================"
echo "Ready to implement Spec 004"
echo "========================================"
