#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Feature: Branch View Enhancement with All-Tests Display and Timeline

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/home/ewyct/dev/lastest2"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start after ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."
cd "$PROJECT_ROOT"

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    pnpm install
fi

# Start Next.js dev server in background
pnpm dev &
NEXT_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Key Pages for this feature:"
echo "  Compare Page: http://localhost:3000/compare"
echo "  Runs Page:    http://localhost:3000/run"
echo ""
echo "Process ID: $NEXT_PID"
echo ""
echo "To stop: kill $NEXT_PID"
echo ""
