/**
 * ISO-3166-1 alpha-2 → English short name, plus a normaliser that maps the
 * free-text values found in `User.Country` back to a code.
 */
import type { CountryCode } from "../model/types";

export const COUNTRY_NAMES: Readonly<Record<CountryCode, string>> = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Åland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthélemy",
  BM: "Bermuda",
  BN: "Brunei Darussalam",
  BO: "Bolivia",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands",
  CD: "Congo, Democratic Republic of the",
  CF: "Central African Republic",
  CG: "Congo",
  CH: "Switzerland",
  CI: "Côte d'Ivoire",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cabo Verde",
  CW: "Curaçao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czechia",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia and the South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard Island and McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "Saint Kitts and Nevis",
  KP: "Korea, Democratic People's Republic of",
  KR: "Korea, Republic of",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Lao People's Democratic Republic",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "Saint Martin (French part)",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Macao",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  PN: "Pitcairn",
  PR: "Puerto Rico",
  PS: "Palestine, State of",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russian Federation",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "Sao Tome and Principe",
  SV: "El Salvador",
  SX: "Sint Maarten (Dutch part)",
  SY: "Syrian Arab Republic",
  SZ: "Eswatini",
  TC: "Turks and Caicos Islands",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Türkiye",
  TT: "Trinidad and Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "United States Minor Outlying Islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Holy See",
  VC: "Saint Vincent and the Grenadines",
  VE: "Venezuela",
  VG: "Virgin Islands (British)",
  VI: "Virgin Islands (U.S.)",
  VN: "Viet Nam",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  WS: "Samoa",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

/** Common alternative spellings / native names / alpha-3 codes → alpha-2. */
const ALIASES: Readonly<Record<string, CountryCode>> = {
  "UNITED STATES OF AMERICA": "US",
  USA: "US",
  "U.S.A.": "US",
  "U.S.": "US",
  AMERICA: "US",
  "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND": "GB",
  UK: "GB",
  "U.K.": "GB",
  "GREAT BRITAIN": "GB",
  ENGLAND: "GB",
  SCOTLAND: "GB",
  WALES: "GB",
  "NORTHERN IRELAND": "GB",
  DEUTSCHLAND: "DE",
  ÖSTERREICH: "AT",
  OESTERREICH: "AT",
  SCHWEIZ: "CH",
  SUISSE: "CH",
  SVIZZERA: "CH",
  ESPAÑA: "ES",
  ESPANA: "ES",
  ITALIA: "IT",
  NEDERLAND: "NL",
  "THE NETHERLANDS": "NL",
  HOLLAND: "NL",
  BELGIQUE: "BE",
  BELGIË: "BE",
  BELGIE: "BE",
  SVERIGE: "SE",
  NORGE: "NO",
  DANMARK: "DK",
  SUOMI: "FI",
  POLSKA: "PL",
  "CZECH REPUBLIC": "CZ",
  ČESKO: "CZ",
  MAGYARORSZÁG: "HU",
  ELLADA: "GR",
  ΕΛΛΆΔΑ: "GR",
  BRASIL: "BR",
  MÉXICO: "MX",
  MEJICO: "MX",
  "REPUBLIC OF KOREA": "KR",
  "SOUTH KOREA": "KR",
  KOREA: "KR",
  "NORTH KOREA": "KP",
  RUSSIA: "RU",
  TURKEY: "TR",
  VIETNAM: "VN",
  "IVORY COAST": "CI",
  "CAPE VERDE": "CV",
  SWAZILAND: "SZ",
  MACEDONIA: "MK",
  "REPUBLIC OF CHINA": "TW",
  "PEOPLE'S REPUBLIC OF CHINA": "CN",
  "HONG KONG SAR": "HK",
  MACAU: "MO",
  UAE: "AE",
  KSA: "SA",
  SAUDI: "SA",
  "REPUBLIC OF IRELAND": "IE",
  EIRE: "IE",
  "SLOVAK REPUBLIC": "SK",
  "BOLIVIA (PLURINATIONAL STATE OF)": "BO",
  "VENEZUELA (BOLIVARIAN REPUBLIC OF)": "VE",
  "IRAN (ISLAMIC REPUBLIC OF)": "IR",
  "TANZANIA, UNITED REPUBLIC OF": "TZ",
  "MOLDOVA, REPUBLIC OF": "MD",
  "TAIWAN, PROVINCE OF CHINA": "TW",
  "VIRGIN ISLANDS, BRITISH": "VG",
  "VIRGIN ISLANDS, U.S.": "VI",
  "MICRONESIA (FEDERATED STATES OF)": "FM",
  LAOS: "LA",
  SYRIA: "SY",
  BRUNEI: "BN",
  PALESTINE: "PS",
  VATICAN: "VA",
  "VATICAN CITY": "VA",
  "MYANMAR (BURMA)": "MM",
  BURMA: "MM",
  "EAST TIMOR": "TL",
  "FALKLAND ISLANDS (MALVINAS)": "FK",
  "CONGO, THE DEMOCRATIC REPUBLIC OF THE": "CD",
  "DR CONGO": "CD",
  DRC: "CD",
  "ST. LUCIA": "LC",
  "ST LUCIA": "LC",
  "ST. KITTS AND NEVIS": "KN",
  "ST. VINCENT AND THE GRENADINES": "VC",
  "THE BAHAMAS": "BS",
  "THE GAMBIA": "GM",
  "TRINIDAD & TOBAGO": "TT",
  "BOSNIA & HERZEGOVINA": "BA",
  "ANTIGUA & BARBUDA": "AG",
};

let byName: Map<string, CountryCode> | undefined;

function nameIndex(): Map<string, CountryCode> {
  if (!byName) {
    byName = new Map();
    for (const [code, name] of Object.entries(COUNTRY_NAMES)) {
      byName.set(name.toUpperCase(), code);
      byName.set(stripDiacritics(name).toUpperCase(), code);
    }
    for (const [alias, code] of Object.entries(ALIASES)) {
      byName.set(alias, code);
      byName.set(stripDiacritics(alias), code);
    }
  }
  return byName;
}

function stripDiacritics(s: string): string {
  return s.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

/** `true` when `code` is a known ISO-3166-1 alpha-2 code. */
export function isCountryCode(code: string): boolean {
  return Object.prototype.hasOwnProperty.call(COUNTRY_NAMES, code);
}

/** English short name for a code, or the code itself when unknown. */
export function countryName(code: CountryCode): string {
  return COUNTRY_NAMES[code] ?? code;
}

/**
 * Normalises a raw country value (ISO code in any case, English or native
 * name, common alias) to an upper-case alpha-2 code. Returns `null` when the
 * value is empty or not recognised.
 */
export function normalizeCountry(
  raw: string | null | undefined,
): CountryCode | null {
  if (raw == null) return null;
  const trimmed = raw.trim();
  if (!trimmed) return null;
  const upper = trimmed.toUpperCase();
  if (upper.length === 2 && isCountryCode(upper)) return upper;
  const idx = nameIndex();
  const direct = idx.get(upper) ?? idx.get(stripDiacritics(upper));
  if (direct) return direct;
  // "Germany (DE)" / "DE - Germany" style values
  const paren = upper.match(/\(([A-Z]{2})\)/);
  if (paren?.[1] && isCountryCode(paren[1])) return paren[1];
  const prefix = upper.match(/^([A-Z]{2})\s*[-–:]/);
  if (prefix?.[1] && isCountryCode(prefix[1])) return prefix[1];
  return null;
}
