import type { SelectorConfig, StabilizationSettings } from '@/lib/db/schema';
import { DEFAULT_STABILIZATION_SETTINGS } from '@/lib/db/schema';

export const TESTING_TEMPLATE_IDS = [
  'saas',
  'marketing',
  'canvas',
  'ecommerce',
  'documentation',
  'mobile-first',
  'spa',
  'cms',
  'custom',
] as const;

export type TestingTemplateId = (typeof TESTING_TEMPLATE_IDS)[number];

export interface TestingTemplateSettings {
  // Browser
  browser: string;
  headlessMode: string;
  viewportWidth: number;
  viewportHeight: number;
  navigationTimeout: number;
  actionTimeout: number;
  // Recording
  defaultRecordingEngine: string;
  pointerGestures: boolean;
  cursorFPS: number;
  // Snapshot
  freezeAnimations: boolean;
  screenshotDelay: number;
  maxParallelTests: number;
  // Selectors
  selectorPriority: SelectorConfig[];
  // Stabilization
  stabilization: StabilizationSettings;
  // Diff sensitivity
  diff: {
    unchangedThreshold: number;
    flakyThreshold: number;
    includeAntiAliasing: boolean;
    ignorePageShift: boolean;
  };
}

export interface TestingTemplate {
  name: string;
  description: string;
  icon: string;
  settings: TestingTemplateSettings;
}

export const TESTING_TEMPLATES: Record<Exclude<TestingTemplateId, 'custom'>, TestingTemplate> = {
  saas: {
    name: 'SaaS / Dashboard',
    description: 'Data-heavy dashboards with dynamic content, timestamps, and charts',
    icon: 'LayoutDashboard',
    settings: {
      browser: 'chromium',
      headlessMode: 'true',
      viewportWidth: 1920,
      viewportHeight: 1080,
      navigationTimeout: 45000,
      actionTimeout: 10000,
      defaultRecordingEngine: 'lastest',
      pointerGestures: false,
      cursorFPS: 30,
      freezeAnimations: true,
      screenshotDelay: 500,
      maxParallelTests: 2,
      selectorPriority: [
        { type: 'data-testid', enabled: true, priority: 1 },
        { type: 'id', enabled: true, priority: 2 },
        { type: 'role-name', enabled: true, priority: 3 },
        { type: 'aria-label', enabled: true, priority: 4 },
        { type: 'text', enabled: true, priority: 5 },
        { type: 'placeholder', enabled: true, priority: 6 },
        { type: 'name', enabled: true, priority: 7 },
        { type: 'css-path', enabled: true, priority: 8 },
        { type: 'ocr-text', enabled: false, priority: 9 },
        { type: 'coords', enabled: true, priority: 10 },
      ],
      stabilization: {
        ...DEFAULT_STABILIZATION_SETTINGS,
        waitForNetworkIdle: true,
        networkIdleTimeout: 8000,
        waitForDomStable: true,
        domStableTimeout: 3000,
        waitForFonts: true,
        freezeTimestamps: true,
        freezeRandomValues: true,
        mockThirdPartyImages: true,
        hideLoadingIndicators: true,
        autoMaskDynamicContent: true,
        maskPatterns: ['timestamps', 'uuids', 'relative-times'],
      },
      diff: {
        unchangedThreshold: 0.5,
        flakyThreshold: 5,
        includeAntiAliasing: true,
        ignorePageShift: false,
      },
    },
  },
  marketing: {
    name: 'Marketing Website',
    description: 'Static marketing pages with third-party scripts and hero images',
    icon: 'Globe',
    settings: {
      browser: 'chromium',
      headlessMode: 'true',
      viewportWidth: 1440,
      viewportHeight: 900,
      navigationTimeout: 30000,
      actionTimeout: 5000,
      defaultRecordingEngine: 'lastest',
      pointerGestures: false,
      cursorFPS: 30,
      freezeAnimations: true,
      screenshotDelay: 300,
      maxParallelTests: 3,
      selectorPriority: [
        { type: 'data-testid', enabled: true, priority: 1 },
        { type: 'id', enabled: true, priority: 2 },
        { type: 'role-name', enabled: true, priority: 3 },
        { type: 'text', enabled: true, priority: 4 },
        { type: 'aria-label', enabled: true, priority: 5 },
        { type: 'placeholder', enabled: true, priority: 6 },
        { type: 'ocr-text', enabled: true, priority: 7 },
        { type: 'name', enabled: true, priority: 8 },
        { type: 'css-path', enabled: true, priority: 9 },
        { type: 'coords', enabled: true, priority: 10 },
      ],
      stabilization: {
        ...DEFAULT_STABILIZATION_SETTINGS,
        waitForNetworkIdle: true,
        networkIdleTimeout: 5000,
        waitForDomStable: true,
        domStableTimeout: 2000,
        waitForFonts: true,
        freezeTimestamps: false,
        freezeRandomValues: false,
        blockThirdParty: true,
        mockThirdPartyImages: true,
        hideLoadingIndicators: true,
      },
      diff: {
        unchangedThreshold: 1,
        flakyThreshold: 8,
        includeAntiAliasing: false,
        ignorePageShift: true,
      },
    },
  },
  canvas: {
    name: 'Canvas / Drawing',
    description: 'WebGL, canvas-based, or drawing apps with rendering variability',
    icon: 'Palette',
    settings: {
      browser: 'chromium',
      headlessMode: 'shell',
      viewportWidth: 1920,
      viewportHeight: 1080,
      navigationTimeout: 60000,
      actionTimeout: 15000,
      defaultRecordingEngine: 'lastest',
      pointerGestures: true,
      cursorFPS: 60,
      freezeAnimations: true,
      screenshotDelay: 1000,
      maxParallelTests: 1,
      selectorPriority: [
        { type: 'coords', enabled: true, priority: 1 },
        { type: 'data-testid', enabled: true, priority: 2 },
        { type: 'css-path', enabled: true, priority: 3 },
        { type: 'ocr-text', enabled: true, priority: 4 },
        { type: 'id', enabled: true, priority: 5 },
        { type: 'role-name', enabled: true, priority: 6 },
        { type: 'aria-label', enabled: true, priority: 7 },
        { type: 'text', enabled: true, priority: 8 },
        { type: 'placeholder', enabled: true, priority: 9 },
        { type: 'name', enabled: true, priority: 10 },
      ],
      stabilization: {
        ...DEFAULT_STABILIZATION_SETTINGS,
        waitForNetworkIdle: true,
        networkIdleTimeout: 10000,
        waitForDomStable: true,
        domStableTimeout: 5000,
        waitForFonts: true,
        freezeTimestamps: true,
        freezeRandomValues: true,
        mockThirdPartyImages: true,
        hideLoadingIndicators: true,
        crossOsConsistency: true,
        disableWebfonts: true,
        burstCapture: true,
        burstFrameCount: 5,
        burstStabilityThreshold: 0.3,
      },
      diff: {
        unchangedThreshold: 0.3,
        flakyThreshold: 3,
        includeAntiAliasing: true,
        ignorePageShift: false,
      },
    },
  },
  ecommerce: {
    name: 'E-commerce',
    description: 'Product catalogs with prices, images, and dynamic cart content',
    icon: 'ShoppingCart',
    settings: {
      browser: 'chromium',
      headlessMode: 'true',
      viewportWidth: 1440,
      viewportHeight: 900,
      navigationTimeout: 45000,
      actionTimeout: 10000,
      defaultRecordingEngine: 'lastest',
      pointerGestures: false,
      cursorFPS: 30,
      freezeAnimations: true,
      screenshotDelay: 500,
      maxParallelTests: 2,
      selectorPriority: [
        { type: 'data-testid', enabled: true, priority: 1 },
        { type: 'id', enabled: true, priority: 2 },
        { type: 'role-name', enabled: true, priority: 3 },
        { type: 'aria-label', enabled: true, priority: 4 },
        { type: 'text', enabled: true, priority: 5 },
        { type: 'placeholder', enabled: true, priority: 6 },
        { type: 'name', enabled: true, priority: 7 },
        { type: 'css-path', enabled: true, priority: 8 },
        { type: 'ocr-text', enabled: false, priority: 9 },
        { type: 'coords', enabled: true, priority: 10 },
      ],
      stabilization: {
        ...DEFAULT_STABILIZATION_SETTINGS,
        waitForNetworkIdle: true,
        networkIdleTimeout: 8000,
        waitForDomStable: true,
        domStableTimeout: 3000,
        waitForFonts: true,
        freezeTimestamps: true,
        freezeRandomValues: true,
        mockThirdPartyImages: true,
        hideLoadingIndicators: true,
        autoMaskDynamicContent: true,
        maskPatterns: ['timestamps', 'uuids', 'relative-times'],
      },
      diff: {
        unchangedThreshold: 0.5,
        flakyThreshold: 8,
        includeAntiAliasing: false,
        ignorePageShift: true,
      },
    },
  },
  documentation: {
    name: 'Documentation',
    description: 'Mostly static text content with code blocks and minimal JS',
    icon: 'BookOpen',
    settings: {
      browser: 'chromium',
      headlessMode: 'true',
      viewportWidth: 1280,
      viewportHeight: 720,
      navigationTimeout: 15000,
      actionTimeout: 5000,
      defaultRecordingEngine: 'lastest',
      pointerGestures: false,
      cursorFPS: 30,
      freezeAnimations: false,
      screenshotDelay: 0,
      maxParallelTests: 4,
      selectorPriority: [
        { type: 'data-testid', enabled: true, priority: 1 },
        { type: 'text', enabled: true, priority: 2 },
        { type: 'id', enabled: true, priority: 3 },
        { type: 'role-name', enabled: true, priority: 4 },
        { type: 'aria-label', enabled: true, priority: 5 },
        { type: 'placeholder', enabled: true, priority: 6 },
        { type: 'ocr-text', enabled: true, priority: 7 },
        { type: 'name', enabled: true, priority: 8 },
        { type: 'css-path', enabled: true, priority: 9 },
        { type: 'coords', enabled: true, priority: 10 },
      ],
      stabilization: {
        ...DEFAULT_STABILIZATION_SETTINGS,
        waitForNetworkIdle: true,
        networkIdleTimeout: 3000,
        waitForDomStable: true,
        domStableTimeout: 1000,
        waitForFonts: true,
        freezeTimestamps: false,
        freezeRandomValues: false,
        mockThirdPartyImages: true,
        hideLoadingIndicators: true,
        crossOsConsistency: true,
      },
      diff: {
        unchangedThreshold: 0.1,
        flakyThreshold: 2,
        includeAntiAliasing: false,
        ignorePageShift: true,
      },
    },
  },
  'mobile-first': {
    name: 'Mobile-First',
    description: 'Mobile viewport with touch interactions and responsive layouts',
    icon: 'Smartphone',
    settings: {
      browser: 'webkit',
      headlessMode: 'true',
      viewportWidth: 390,
      viewportHeight: 844,
      navigationTimeout: 30000,
      actionTimeout: 8000,
      defaultRecordingEngine: 'lastest',
      pointerGestures: true,
      cursorFPS: 30,
      freezeAnimations: true,
      screenshotDelay: 300,
      maxParallelTests: 2,
      selectorPriority: [
        { type: 'data-testid', enabled: true, priority: 1 },
        { type: 'aria-label', enabled: true, priority: 2 },
        { type: 'id', enabled: true, priority: 3 },
        { type: 'role-name', enabled: true, priority: 4 },
        { type: 'text', enabled: true, priority: 5 },
        { type: 'placeholder', enabled: true, priority: 6 },
        { type: 'name', enabled: true, priority: 7 },
        { type: 'css-path', enabled: true, priority: 8 },
        { type: 'ocr-text', enabled: false, priority: 9 },
        { type: 'coords', enabled: true, priority: 10 },
      ],
      stabilization: {
        ...DEFAULT_STABILIZATION_SETTINGS,
        waitForNetworkIdle: true,
        networkIdleTimeout: 5000,
        waitForDomStable: true,
        domStableTimeout: 2000,
        waitForFonts: true,
        freezeTimestamps: true,
        freezeRandomValues: true,
        mockThirdPartyImages: true,
        hideLoadingIndicators: true,
        crossOsConsistency: true,
      },
      diff: {
        unchangedThreshold: 1,
        flakyThreshold: 8,
        includeAntiAliasing: false,
        ignorePageShift: true,
      },
    },
  },
  spa: {
    name: 'SPA',
    description: 'Single-page app with client-side routing and dynamic state',
    icon: 'AppWindow',
    settings: {
      browser: 'chromium',
      headlessMode: 'true',
      viewportWidth: 1920,
      viewportHeight: 1080,
      navigationTimeout: 45000,
      actionTimeout: 10000,
      defaultRecordingEngine: 'lastest',
      pointerGestures: false,
      cursorFPS: 30,
      freezeAnimations: true,
      screenshotDelay: 500,
      maxParallelTests: 2,
      selectorPriority: [
        { type: 'data-testid', enabled: true, priority: 1 },
        { type: 'id', enabled: true, priority: 2 },
        { type: 'role-name', enabled: true, priority: 3 },
        { type: 'aria-label', enabled: true, priority: 4 },
        { type: 'text', enabled: true, priority: 5 },
        { type: 'placeholder', enabled: true, priority: 6 },
        { type: 'name', enabled: true, priority: 7 },
        { type: 'css-path', enabled: true, priority: 8 },
        { type: 'ocr-text', enabled: false, priority: 9 },
        { type: 'coords', enabled: true, priority: 10 },
      ],
      stabilization: {
        ...DEFAULT_STABILIZATION_SETTINGS,
        waitForNetworkIdle: true,
        networkIdleTimeout: 8000,
        waitForDomStable: true,
        domStableTimeout: 3000,
        waitForFonts: true,
        freezeTimestamps: true,
        freezeRandomValues: true,
        mockThirdPartyImages: true,
        hideLoadingIndicators: true,
      },
      diff: {
        unchangedThreshold: 0.5,
        flakyThreshold: 5,
        includeAntiAliasing: false,
        ignorePageShift: false,
      },
    },
  },
  cms: {
    name: 'CMS',
    description: 'Content management systems with rich editors, media, and loaders',
    icon: 'FileEdit',
    settings: {
      browser: 'chromium',
      headlessMode: 'true',
      viewportWidth: 1920,
      viewportHeight: 1080,
      navigationTimeout: 45000,
      actionTimeout: 10000,
      defaultRecordingEngine: 'lastest',
      pointerGestures: false,
      cursorFPS: 30,
      freezeAnimations: true,
      screenshotDelay: 500,
      maxParallelTests: 2,
      selectorPriority: [
        { type: 'role-name', enabled: true, priority: 1 },
        { type: 'data-testid', enabled: true, priority: 2 },
        { type: 'id', enabled: true, priority: 3 },
        { type: 'aria-label', enabled: true, priority: 4 },
        { type: 'text', enabled: true, priority: 5 },
        { type: 'placeholder', enabled: true, priority: 6 },
        { type: 'name', enabled: true, priority: 7 },
        { type: 'css-path', enabled: true, priority: 8 },
        { type: 'ocr-text', enabled: false, priority: 9 },
        { type: 'coords', enabled: true, priority: 10 },
      ],
      stabilization: {
        ...DEFAULT_STABILIZATION_SETTINGS,
        waitForNetworkIdle: true,
        networkIdleTimeout: 8000,
        waitForDomStable: true,
        domStableTimeout: 3000,
        waitForFonts: true,
        freezeTimestamps: true,
        freezeRandomValues: true,
        mockThirdPartyImages: true,
        hideLoadingIndicators: true,
        autoMaskDynamicContent: true,
        maskPatterns: ['timestamps', 'uuids', 'relative-times'],
      },
      diff: {
        unchangedThreshold: 0.5,
        flakyThreshold: 8,
        includeAntiAliasing: false,
        ignorePageShift: true,
      },
    },
  },
};

export function isValidTemplateId(id: string): id is TestingTemplateId {
  return TESTING_TEMPLATE_IDS.includes(id as TestingTemplateId);
}
