#!/bin/bash

# Auto-Build Environment Setup for Spec 008
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
pnpm install

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."
pnpm dev &
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js:  http://localhost:3000"
echo ""
echo "Bug Fix Task:"
echo "  - Test recordings will be saved to ./public/screenshots/{repositoryId}/"
echo "  - Test runs will be saved to ./public/screenshots/{repositoryId}/"
echo ""
echo "To test:"
echo "  1. Navigate to http://localhost:3000/record"
echo "  2. Create a test recording"
echo "  3. Verify screenshot location"
echo ""
