import type { GitlabPipelineMode, GitlabPipelineTriggerEvent } from '@/lib/db/schema';

const RUNNER_VERSION = '0.4.2';

export interface CiYamlConfig {
  mode: GitlabPipelineMode;
  projectPath: string; // "namespace/project"
  triggerEvents: GitlabPipelineTriggerEvent[];
  branchFilter: string[];
  timeout: number; // ms
  failOnChanges: boolean;
}

function escapeRegexBranch(b: string): string {
  return b.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function buildRules(config: CiYamlConfig): string[] {
  const branchPattern = config.branchFilter.length > 0
    ? `/^(${config.branchFilter.map(escapeRegexBranch).join('|')})$/`
    : null;
  const lines: string[] = [];
  for (const event of config.triggerEvents) {
    if (event === 'merge_request') {
      lines.push(`    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'`);
      continue;
    }
    if (event === 'push') {
      const cond = branchPattern
        ? `$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ ${branchPattern}`
        : `$CI_PIPELINE_SOURCE == "push"`;
      lines.push(`    - if: '${cond}'`);
      continue;
    }
    if (event === 'schedule') {
      lines.push(`    - if: '$CI_PIPELINE_SOURCE == "schedule"'`);
      continue;
    }
    if (event === 'manual') {
      lines.push(`    - if: '$CI_PIPELINE_SOURCE == "web"'`);
    }
  }
  if (lines.length === 0) {
    lines.push(`    - if: '$CI_PIPELINE_SOURCE == "push"'`);
  }
  return lines;
}

function buildTriggerCommand(config: CiYamlConfig): string {
  const flags: string[] = [];
  flags.push('-t "$LASTEST_TOKEN"');
  flags.push('-s "$LASTEST_URL"');
  flags.push(`--repo "${config.projectPath}"`);
  flags.push(`--branch "$CI_COMMIT_REF_NAME"`);
  flags.push(`--commit "$CI_COMMIT_SHA"`);
  if (config.failOnChanges) flags.push('--fail-on-changes');
  flags.push(`--timeout ${config.timeout}`);
  return [
    `      npx @lastest/runner@${RUNNER_VERSION} trigger \\`,
    ...flags.map((f, i) => i === flags.length - 1 ? `        ${f}` : `        ${f} \\`),
  ].join('\n');
}

function buildPersistentScript(config: CiYamlConfig): string {
  return [
    '  script:',
    buildTriggerCommand(config),
  ].join('\n');
}

function buildEphemeralScript(config: CiYamlConfig): string {
  return [
    '  before_script:',
    `    - npx @lastest/runner@${RUNNER_VERSION} run -t "$LASTEST_TOKEN" -s "$LASTEST_URL" &`,
    '    - export RUNNER_PID=$!',
    '    - sleep 3',
    '  script:',
    buildTriggerCommand(config),
    '  after_script:',
    '    - kill $RUNNER_PID || true',
  ].join('\n');
}

export function generateCiYaml(config: CiYamlConfig): string {
  const rules = buildRules(config);
  const isEphemeral = config.mode === 'ephemeral';
  const stage = isEphemeral
    ? [
        '  image: mcr.microsoft.com/playwright:v1.49.0-jammy',
        ...buildEphemeralScript(config).split('\n'),
      ].join('\n')
    : [
        '  image: node:20-bookworm',
        ...buildPersistentScript(config).split('\n'),
      ].join('\n');

  return `# Generated by Lastest — Visual Regression Tests
stages:
  - test

lastest-visual-tests:
  stage: test
${stage}
  rules:
${rules.join('\n')}
`;
}
